name: Build and Publish Docker image

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  build-test-push:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      # -----------------------------------------------------------------------
      # Build the Docker image (with dev/test tools inside your Dockerfile)
      # -----------------------------------------------------------------------
      - name: Build image (for test)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true                # load image into local runner
          tags: bdns-ingest:test    # local test tag

      # -----------------------------------------------------------------------
      # Run lint & tests inside the container
      # Override the entrypoint so we can call `make` directly
      # -----------------------------------------------------------------------
      - name: Run shellcheck
        run: docker run --rm --entrypoint "" -v $PWD:/src -w /src bdns-ingest:test make shellcheck

      - name: Run tests
        run: docker run --rm --entrypoint "" -v $PWD:/src -w /src bdns-ingest:test make test

      # -----------------------------------------------------------------------
      # Push the image only if everything passed
      # -----------------------------------------------------------------------
      - name: Log in to GitHub Container Registry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push release image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bdns-ingest:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/bdns-ingest:latest

  dockerhub-push:
    needs: build-test-push
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bdns-ingest:latest
